/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_tcc_prototipo;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduarte
 */
public class tela_jogo3 extends javax.swing.JFrame {
    
    javax.swing.JLabel label_anterior = null;
    Lista_bloco_jlabel lista_de_labels = Lista_bloco_jlabel.getInstancia();
    private boolean jogoFinalizado = false;

    /**
     * Creates new form tela_jogo1
     */
    public tela_jogo3() {
        initComponents();
        this.setLocationRelativeTo(null);
        g_jogoActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4_1 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5_1 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8_1 = new javax.swing.JLabel();
        b8_2 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        b11 = new javax.swing.JLabel();
        b12_1 = new javax.swing.JLabel();
        b12_2 = new javax.swing.JLabel();
        b12 = new javax.swing.JLabel();
        b13 = new javax.swing.JLabel();
        b14 = new javax.swing.JLabel();
        b15 = new javax.swing.JLabel();
        b16_2 = new javax.swing.JLabel();
        b16 = new javax.swing.JLabel();
        b17 = new javax.swing.JLabel();
        b18 = new javax.swing.JLabel();
        b19 = new javax.swing.JLabel();
        b20 = new javax.swing.JLabel();
        b21_2 = new javax.swing.JLabel();
        b21 = new javax.swing.JLabel();
        b22 = new javax.swing.JLabel();
        b23 = new javax.swing.JLabel();
        b24 = new javax.swing.JLabel();
        b25 = new javax.swing.JLabel();
        g_jogo = new javax.swing.JButton();
        corrigir = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLjogos_concluidos = new javax.swing.JLabel();
        jLcorrecoes_utilizadas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modelo 3");

        jPanel1.setLayout(null);

        b1.setBackground(new java.awt.Color(153, 153, 153));
        b1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha4.png"))); // NOI18N
        b1.setToolTipText("");
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b1);
        b1.setBounds(0, 0, 100, 100);

        b2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha4.png"))); // NOI18N
        b2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b2);
        b2.setBounds(100, 0, 100, 100);

        b3.setBackground(new java.awt.Color(153, 153, 153));
        b3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha4.png"))); // NOI18N
        b3.setToolTipText("");
        b3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b3);
        b3.setBounds(200, 0, 100, 100);

        b4_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b4_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b4_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(b4_1);
        b4_1.setBounds(300, 50, 100, 50);

        b4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha3.png"))); // NOI18N
        b4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b4);
        b4.setBounds(300, 0, 100, 100);

        b5_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b5_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b5_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(b5_1);
        b5_1.setBounds(400, 50, 100, 50);

        b5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha3.png"))); // NOI18N
        b5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b5);
        b5.setBounds(400, 0, 100, 100);

        b6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha4.png"))); // NOI18N
        b6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b6);
        b6.setBounds(0, 100, 100, 100);

        b7.setBackground(new java.awt.Color(153, 153, 153));
        b7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha4.png"))); // NOI18N
        b7.setToolTipText("");
        b7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b7);
        b7.setBounds(100, 100, 100, 100);

        b8_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b8_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b8_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(b8_1);
        b8_1.setBounds(200, 150, 100, 50);

        b8_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b8_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        b8_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(b8_2);
        b8_2.setBounds(200, 100, 100, 50);

        b8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha.png"))); // NOI18N
        b8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b8);
        b8.setBounds(200, 100, 100, 100);

        b9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b9MouseClicked(evt);
            }
        });
        jPanel1.add(b9);
        b9.setBounds(300, 100, 100, 100);

        b10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b10MouseClicked(evt);
            }
        });
        jPanel1.add(b10);
        b10.setBounds(400, 100, 100, 100);

        b11.setBackground(new java.awt.Color(153, 153, 153));
        b11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha4.png"))); // NOI18N
        b11.setToolTipText("");
        b11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b11);
        b11.setBounds(0, 200, 100, 100);

        b12_1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b12_1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        b12_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(b12_1);
        b12_1.setBounds(100, 250, 100, 50);

        b12_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b12_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        b12_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(b12_2);
        b12_2.setBounds(100, 200, 100, 50);

        b12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha.png"))); // NOI18N
        b12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b12);
        b12.setBounds(100, 200, 100, 100);

        b13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b13MouseClicked(evt);
            }
        });
        jPanel1.add(b13);
        b13.setBounds(200, 200, 100, 100);

        b14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b14MouseClicked(evt);
            }
        });
        jPanel1.add(b14);
        b14.setBounds(300, 200, 100, 100);

        b15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b15MouseClicked(evt);
            }
        });
        jPanel1.add(b15);
        b15.setBounds(400, 200, 100, 100);

        b16_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b16_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        b16_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(b16_2);
        b16_2.setBounds(0, 300, 100, 50);

        b16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha2.png"))); // NOI18N
        b16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b16);
        b16.setBounds(0, 300, 100, 100);

        b17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b17MouseClicked(evt);
            }
        });
        jPanel1.add(b17);
        b17.setBounds(100, 300, 100, 100);

        b18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b18MouseClicked(evt);
            }
        });
        jPanel1.add(b18);
        b18.setBounds(200, 300, 100, 100);

        b19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b19MouseClicked(evt);
            }
        });
        jPanel1.add(b19);
        b19.setBounds(300, 300, 100, 100);

        b20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b20MouseClicked(evt);
            }
        });
        jPanel1.add(b20);
        b20.setBounds(400, 300, 100, 100);

        b21_2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        b21_2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        b21_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel1.add(b21_2);
        b21_2.setBounds(0, 400, 100, 50);

        b21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Linha2.png"))); // NOI18N
        b21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        jPanel1.add(b21);
        b21.setBounds(0, 400, 100, 100);

        b22.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b22MouseClicked(evt);
            }
        });
        jPanel1.add(b22);
        b22.setBounds(100, 400, 100, 100);

        b23.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b23MouseClicked(evt);
            }
        });
        jPanel1.add(b23);
        b23.setBounds(200, 400, 100, 100);

        b24.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b24MouseClicked(evt);
            }
        });
        jPanel1.add(b24);
        b24.setBounds(300, 400, 100, 100);

        b25.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        b25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        b25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b25MouseClicked(evt);
            }
        });
        jPanel1.add(b25);
        b25.setBounds(400, 400, 100, 100);

        g_jogo.setText("Novo Jogo");
        g_jogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g_jogoActionPerformed(evt);
            }
        });

        corrigir.setText("Corrigir");
        corrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrigirActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Jogos concluidos:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Correções utilizadas:");

        jLjogos_concluidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLjogos_concluidos.setText("00000");

        jLcorrecoes_utilizadas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLcorrecoes_utilizadas.setText("00000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(g_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(corrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLjogos_concluidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLcorrecoes_utilizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(corrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(g_jogo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLjogos_concluidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLcorrecoes_utilizadas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b10MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b10,jogoFinalizado);
    }//GEN-LAST:event_b10MouseClicked

    private void b9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b9MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b9,jogoFinalizado);
    }//GEN-LAST:event_b9MouseClicked

    private void b13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b13MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b13,jogoFinalizado);
    }//GEN-LAST:event_b13MouseClicked

    private void b14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b14MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b14,jogoFinalizado);
    }//GEN-LAST:event_b14MouseClicked

    private void b17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b17MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b17,jogoFinalizado);
    }//GEN-LAST:event_b17MouseClicked

    private void b20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b20MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b20,jogoFinalizado);
    }//GEN-LAST:event_b20MouseClicked

    private void b19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b19MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b19,jogoFinalizado);
    }//GEN-LAST:event_b19MouseClicked

    private void b22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b22MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b22,jogoFinalizado);
    }//GEN-LAST:event_b22MouseClicked

    private void b23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b23MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b23,jogoFinalizado);
    }//GEN-LAST:event_b23MouseClicked

    private void b25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b25MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b25,jogoFinalizado);
    }//GEN-LAST:event_b25MouseClicked

    private void g_jogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g_jogoActionPerformed
        // TODO add your handling code here:
        //atualiza a pontuação
        Pontuacao pontos = Pontuacao.getInstancia();
        jLcorrecoes_utilizadas.setText(String.valueOf(pontos.getNumCorrecoes()));
        jLjogos_concluidos.setText(String.valueOf(pontos.getNumTabelasCompletas()));
        //--------------------
        jogoFinalizado = false;
        Matriz m = Matriz.getInstancia();
        m.Gerar_matriz3();
        m.Gerar_jogo_matrizX();
        Lista_bloco_jlabel lista = Organizar_labels();
        Tratamentos_tela_jogo tratamento = new Tratamentos_tela_jogo();
        tratamento.novo_jogo(m, lista);
    }//GEN-LAST:event_g_jogoActionPerformed

    private void corrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrigirActionPerformed
        // TODO add your handling code here:
        if(!jogoFinalizado){            
            Lista_bloco_jlabel labels = Lista_bloco_jlabel.getInstancia();
            Matriz m = Matriz.getInstancia();
            Tratamentos_tela_jogo t = new Tratamentos_tela_jogo();
            jogoFinalizado = t.corrigir_e_exibir_na_tela(labels, m);
            Pontuacao pontos = Pontuacao.getInstancia();
            pontos.setNumCorrecoes(pontos.getNumCorrecoes()+1);
            jLcorrecoes_utilizadas.setText(String.valueOf(pontos.getNumCorrecoes()));
            if(jogoFinalizado){
                pontos.setNumTabelasCompletas(pontos.getNumTabelasCompletas()+1);
                jLjogos_concluidos.setText(String.valueOf(pontos.getNumTabelasCompletas()));
            }
        }else{
            JOptionPane.showMessageDialog(null, "Você já finalizou este jogo, clique em Novo Jogo");
        }
    }//GEN-LAST:event_corrigirActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        Matriz.deletarInstancia();
        Lista_bloco_jlabel.deletarInstancia();
        new Tela_inicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void b15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b15MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b15,jogoFinalizado);
    }//GEN-LAST:event_b15MouseClicked

    private void b18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b18MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b18,jogoFinalizado);
    }//GEN-LAST:event_b18MouseClicked

    private void b24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b24MouseClicked
        // TODO add your handling code here:
        label_anterior = Tratamentos_tela_jogo.click_na_label(label_anterior, b24,jogoFinalizado);
    }//GEN-LAST:event_b24MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_jogo3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_jogo3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_jogo3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_jogo3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_jogo3().setVisible(true);
            }
        });
    }
    
    private Lista_bloco_jlabel Organizar_labels(){
        Lista_bloco_jlabel conjunto = Lista_bloco_jlabel.getInstancia();
        
        conjunto.getBloco_matriz()[0][0] = new Bloco_jlabel(b1, null, null);
        conjunto.getBloco_matriz()[0][1] = new Bloco_jlabel(b2, null, null);
        conjunto.getBloco_matriz()[0][2] = new Bloco_jlabel(b3, null, null);
        conjunto.getBloco_matriz()[0][3] = new Bloco_jlabel(b4, b4_1, null);
        conjunto.getBloco_matriz()[0][4] = new Bloco_jlabel(b5, b5_1, null);
        conjunto.getBloco_matriz()[1][0] = new Bloco_jlabel(b6, null, null);
        conjunto.getBloco_matriz()[1][1] = new Bloco_jlabel(b7, null, null);
        conjunto.getBloco_matriz()[1][2] = new Bloco_jlabel(b8, b8_1, b8_2);
        conjunto.getBloco_matriz()[1][3] = new Bloco_jlabel(b9, null, null);
        conjunto.getBloco_matriz()[1][4] = new Bloco_jlabel(b10, null, null);
        conjunto.getBloco_matriz()[2][0] = new Bloco_jlabel(b11, null, null);
        conjunto.getBloco_matriz()[2][1] = new Bloco_jlabel(b12, b12_1, b12_2);
        conjunto.getBloco_matriz()[2][2] = new Bloco_jlabel(b13, null, null);
        conjunto.getBloco_matriz()[2][3] = new Bloco_jlabel(b14, null, null);
        conjunto.getBloco_matriz()[2][4] = new Bloco_jlabel(b15, null, null);
        conjunto.getBloco_matriz()[3][0] = new Bloco_jlabel(b16, null, b16_2);
        conjunto.getBloco_matriz()[3][1] = new Bloco_jlabel(b17, null, null);
        conjunto.getBloco_matriz()[3][2] = new Bloco_jlabel(b18, null, null);
        conjunto.getBloco_matriz()[3][3] = new Bloco_jlabel(b19, null, null);
        conjunto.getBloco_matriz()[3][4] = new Bloco_jlabel(b20, null, null);
        conjunto.getBloco_matriz()[4][0] = new Bloco_jlabel(b21, null, b21_2);
        conjunto.getBloco_matriz()[4][1] = new Bloco_jlabel(b22, null, null);
        conjunto.getBloco_matriz()[4][2] = new Bloco_jlabel(b23, null, null);
        conjunto.getBloco_matriz()[4][3] = new Bloco_jlabel(b24, null, null);
        conjunto.getBloco_matriz()[4][4] = new Bloco_jlabel(b25, null, null);
        
        return conjunto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b11;
    private javax.swing.JLabel b12;
    private javax.swing.JLabel b12_1;
    private javax.swing.JLabel b12_2;
    private javax.swing.JLabel b13;
    private javax.swing.JLabel b14;
    private javax.swing.JLabel b15;
    private javax.swing.JLabel b16;
    private javax.swing.JLabel b16_2;
    private javax.swing.JLabel b17;
    private javax.swing.JLabel b18;
    private javax.swing.JLabel b19;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b20;
    private javax.swing.JLabel b21;
    private javax.swing.JLabel b21_2;
    private javax.swing.JLabel b22;
    private javax.swing.JLabel b23;
    private javax.swing.JLabel b24;
    private javax.swing.JLabel b25;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b4_1;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b5_1;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b8_1;
    private javax.swing.JLabel b8_2;
    private javax.swing.JLabel b9;
    private javax.swing.JButton corrigir;
    private javax.swing.JButton g_jogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLcorrecoes_utilizadas;
    private javax.swing.JLabel jLjogos_concluidos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
